### ISSUE TITLE
Clarify Domain model and Database structure 

### ISSUE THREAD

**Issue by dzahariev** [Peripli/specification#13]
Define domain model and corresponding data structures that shall be used for persisting the model in database.

**Comment by dotchev** [comment]
Isn't db structure implementation detail?

**Comment by dzahariev** [comment]
Correct!
This issue will be moved in implementation project.

BR,
Dobri

**Comment by dzahariev** [comment]
Moved to: https://github.com/Peripli/service-manager/issues/20
