### ISSUE TITLE
Improve review process

### ISSUE THREAD

**Issue by dpanayotov** [Peripli/specification#19]
Pullapprove-like feature is available in Github by using Code Owners[1]. I think it would be nice to have this for the specification. Have a list of "maintainers" from which a subset must approve a specific pull request before it can be merged. Granted, it lacks the "disable merge" functionality of pullapprove but I think that's sufficient.

[1]https://blog.github.com/2017-07-06-introducing-code-owners/

**Comment by dzahariev** [comment]
For specification repository we change the configuration in following way:
1. We protect the master branch even for administrators
1. Always Require pull request reviews before merging
1. Require 3 approvals before merge
1. Dismiss stale pull request approvals when new commits are pushed
1. Require status checks to pass before merging
1. Require branches to be up to date before merging

If this configuration not works for some cases will adjusts it in to the future.
